### ISSUE TITLE
hdl_path_slice implementation

### ISSUE THREAD

**Issue by soleshka** [SystemRDL/PeakRDL-uvm#8]
Hello once more,
I am trying to implement backdoor access to registers and facing an issue when trying to use hdl_path_slice field  property.

While playing in the actual  register RAL  class definition i noticed that the following  command does what i need :

this.REGNAME.add_hdl_path_slice("REGNAME", 29, 3);

Which eventually writes the relevant 3 msb bits to the regname with backdoor access.

Would you kindly provide a small example how to achieve such a class command using rdl  hdl_path/hdl_path_slice properties ?

I noticed  there is some  mentioning in Spec Errata regarding the hdl_path_slice property, but to be honest i did not understand whether this is a bug or not.

Thank you ,
Oleg Greenberg

**Comment by amykyta3** [comment]
Here is a simple example for how to add a backdoor path in SystemRDL:
```
addrmap top {
    reg {
        field {
            hdl_path_slice = '{"my_reg_f1"};
        } f1[7:0] = 0;
        field {
            hdl_path_slice = '{"my_reg_f2"};
        } f2[15:8] = 0;
    } my_reg;
};
```

I'm totally guessing what the actual backdoor path will be since that will depend on your implementation, but hopefully that helps describe how this works.
In practice, I think you'll find that SystemRDL's hdl path properties are not particularly useful. They work great in the case where you have simple register maps with little repetition. Once you have larger register maps with component re-use and arrays of elements, defining the HDL path inside your RDL becomes pretty cumbersome. The note you found in [my errata page](https://systemrdl-compiler.readthedocs.io/en/latest/dev_notes/rdl_spec_errata.html#definition-of-the-hdl-path-slice-property-is-shortsighted) is describing an ambiguity with the SystemRDL spec itself. My UVM exporter does the best it can when interpreting the hdl path properties, but i think there are bigger issues with how the SystemRDL language defines HDL path properties.

Personally, I think a more practical way of applying HDL paths is to do it purely from the UVM side, and not bothering with embedding them in your SystemRDL. After instantiating the UVM reg model, you can apply HDL paths using the API calls directly to patch in information about your specific hardware usage. If you are using a RTL generator for your register blocks, or have a consistent coding style that your org uses, this process could even be auto-generated off of your RDL with your own custom code generator.

Regarding your comment on how the UVM template is implemented, you're looking at the portion of the template that handles the special case where the slice width is 1 bit. If you look a few lines up, the template handles the more common case where a slice correlates to each field directly:
```
{{inst_ref}}.add_hdl_path_slice("{{field.get_property('hdl_path_slice')[0]}}", {{field.lsb}}, {{field.width}});
```
